apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: guestbook-v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        image: gcr.io/rmlite-playground/guestbook-redis:v2.0.0
        name: php-redis
        ports:
        - containerPort: 80
